.core-defs:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    JNI_PATH: libretro
    CORENAME: easyrpg
    DEPS_VERSION: 1

include:
  - template: Jobs/Code-Quality.gitlab-ci.yml
  - project: 'libretro-infrastructure/ci-templates'
    file: '/linux-x64.yml'
  - project: 'libretro-infrastructure/ci-templates'
    file: '/windows-x64-mingw.yml'
  - project: 'libretro-infrastructure/ci-templates'
    file: '/android-cmake.yml'

stages:
  - build-prepare
  - build-shared
  - build-static
  - test

libretro-build-linux-x64:
  extends:
    - .core-defs
    - .libretro-linux-x64-make-default
  variables:
    DEPS: builds/libretro/buildscripts/linux-static
    CMAKE_ARGS: "
        -DBUILD_SHARED_LIBS=ON
        -DPLAYER_TARGET_PLATFORM=libretro
        -DPLAYER_BUILD_LIBLCF=ON
        -DCMAKE_IGNORE_PATH=/usr/include
        -DCMAKE_BUILD_TYPE=Release"
  cache:
    key: "$CI_COMMIT_REF_SLUG-linux-x64"
    untracked: true
  script:
    - if [ ! -f ${DEPS}/.deps-built.${DEPS_VERSION} ]; then
    - pushd ${DEPS}
    - ./0_build_everything.sh
    - touch .deps-built.${DEPS_VERSION}
    - popd
    - fi
    - cmake ${CMAKE_ARGS} -DCMAKE_PREFIX_PATH=${PWD}/${DEPS}
    - cmake --build . --target easyrpg_libretro -- -j $NUMPROC
    - strip ${CORENAME}_libretro.so

libretro-build-windows-x64-mingw:
  extends:
    - .core-defs
    - .libretro-windows-x64-mingw-make-default
  variables:
    DEPS: builds/libretro/buildscripts/mingw
    CMAKE_ARGS: "
        -DBUILD_SHARED_LIBS=ON
        -DPLAYER_TARGET_PLATFORM=libretro
        -DPLAYER_BUILD_LIBLCF=ON
        -DCMAKE_IGNORE_PATH=/usr/include
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_TOOLCHAIN_FILE=${DEPS}/mingw-w64-x86_64.cmake"
  cache:
    key: "$CI_COMMIT_REF_SLUG-mingw"
    untracked: true
  script:
    - if [ ! -f ${DEPS}/.deps-built.${DEPS_VERSION} ]; then
    - pushd ${DEPS}
    - ./0_build_everything.sh
    - touch .deps-built.${DEPS_VERSION}
    - popd
    - fi
    - cmake ${CMAKE_ARGS} -DCMAKE_PREFIX_PATH=${PWD}/${DEPS} -DCMAKE_CXX_FLAGS="-g0 -O2 -fstack-protector"
    - cmake --build . --target easyrpg_libretro -- -j $NUMPROC

.libretro-android-cmake-easyrpg:
  extends:
    - .core-defs
    - .libretro-android-cmake
  variables:
    DEPS: builds/libretro/buildscripts/android
    CORE_ARGS: "
        -DBUILD_SHARED_LIBS=ON
        -DPLAYER_TARGET_PLATFORM=libretro
        -DPLAYER_BUILD_LIBLCF=ON
        -DCMAKE_IGNORE_PATH=/usr/include
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=BOTH
        -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=BOTH
        -DCMAKE_FIND_ROOT_PATH_MODE_PACKAGE=BOTH"
  cache:
    key: "$CI_COMMIT_REF_SLUG-android"
    untracked: true
#    when: 'always'
  script:
    - if [ ! -f ${DEPS}/.deps-built.${DEPS_VERSION} ]; then
    - pushd ${DEPS}
    - ./0_build_everything.sh
    - touch .deps-built.${DEPS_VERSION}
    - popd
    - fi
    - PLATFORM_ARGS="-DCMAKE_TOOLCHAIN_FILE=$NDK_ROOT/build/cmake/android.toolchain.cmake -DANDROID_STL=c++_static -DANDROID_ABI=$ANDROID_ABI"
    - STRIP=$NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip
    - BUILDDIR=build-$ANDROID_ABI
    - cmake $CORE_ARGS -DCMAKE_PREFIX_PATH=${PWD}/${DEPS}/${ANDROID_ABI}-toolchain $PLATFORM_ARGS . -B$BUILDDIR
    - cmake --build $BUILDDIR --target ${CORENAME}_libretro -- -j $NUMPROC
    - mv $BUILDDIR/${CORENAME}_libretro.so $LIBNAME
    - $STRIP $LIBNAME

android-armeabi-v7a:
  extends: .libretro-android-cmake-easyrpg
  variables:
    ANDROID_ABI: armeabi-v7a

android-arm64-v8a:
  extends: .libretro-android-cmake-easyrpg
  variables:
    ANDROID_ABI: arm64-v8a

android-x86_64:
  extends: .libretro-android-cmake-easyrpg
  variables:
    ANDROID_ABI: x86

android-x86:
  extends: .libretro-android-cmake-easyrpg
  variables:
    ANDROID_ABI: x86_64

